[[constraint]]
  name = "github.com/hattya/go.cli"
  branch = "master"

[[constraint]]
  name = "github.com/hattya/go.diff"
  branch = "master"

[[constraint]]
  name = "golang.org/x/sys"
  branch = "master"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true
